### ISSUE TITLE
Switch GameCube Adapter compatibility

### ISSUE THREAD

**Issue by RobertDaleSmith** [RobertDaleSmith/USBRetro#11]
It was reported that GameCube adapter support was not working with some 3rd-party adapters. I was under the assumption that all of these simulated the vid/pid and USB HID reports of the official WiiU/Switch GameCube USB adapters. So this needs to be researched further to verify.

**Comment by Invictaz** [comment]
You might want to investigate the Mayflash Gamecube USB adapter

https://www.amazon.com/Mayflash-GameCube-Controller-Adapter-Switch/dp/B00RSXRLUE

It's by far the cheapest option.

**Comment by RobertDaleSmith** [comment]
It should work if in Switch mode. But I don’t have this one to verify.
