### ISSUE TITLE
Turbo EverDrive Pro Hot-Heys No Longer Working

### ISSUE THREAD

**Issue by RobertDaleSmith** [RobertDaleSmith/USBRetro#16]
In a recent update the Turbo EverDrive Pro hotkeys workaround patch stopped functioning as it was. Need to revisit this and see what changes caused the single controller buttons to not apply to all multitap reads when hotkeys are detected.

**Comment by RobertDaleSmith** [comment]
Fixed by https://github.com/RobertDaleSmith/USBRetro/commit/70ff5a7d46ccdcada69dd3ea2361585360f16593

**Comment by Outkast92885** [comment]
This isn't working at all for me. I'm on the latest firmware on the USB2PCE and on the Turbo Everdrive Pro.
